### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by peri4n** [nvim-neorg/tree-sitter-norg3#11]
Hi guys,
I'd like to contribute to your tree-sitter grammar. Is this still maintained? If yes, do you have any tasks at hand?
What is the status of the current grammar? 

My longterm goal is to write an LSP for norg files in rust. For this to work I depend on this crate.  There is a different grammar published to crates.io. Which one should one pick, this (unpublished) or the published version?

**Comment by boltlessengineer** [comment]
[v1 parser](https://github.com/nvim-neorg/tree-sitter-norg) is parser what Neorg is currently using.
But it has too many bugs and structure is quite hard to maintain. That’s why we have this v3 parser repo, v1 will be depreciated when v3 parser is done.

Unfortunately process is stalled because of some issues right now.
If you are interested helping parser development, there is [test repo](https://github.com/boltlessengineer/tree-sitter-norg4) aiming to solve them.
We also need [this tree-sitter PR](https://github.com/tree-sitter/tree-sitter/pull/2741) get merged to make/use v3 parser.
